### ISSUE TITLE
input formatting for makam training

### ISSUE THREAD

**Issue by altugkarakurt** [MTG/pycompmusic#10]
I implemented a supervised training function in Python for the makam recoginition studies I'm doing with @sertansenturk. The function is basically called as:

`TrainMakam(makamName, pitchTracks, tonicFreqs)`

makamName is the name of the makam as a string, pitchTracks is an array of pitch tracks of recordings (of the same makam) and tonicFreqs is an array of tonic frequenies of these recordings. The function returns the pitch class model of the trained makam as a json string.

@sertansenturk explained me that the input fomats might change (e.g. pitchTrack can be an array of json strings instead of the current array of arrays). I just wanted to ask what type of input I should be expecting in advance.

**Comment by alastair** [comment]
It makes sense to make this function as generic as possible and use the most basic datatypes as arguments, so array of arrays makes sense. We can convert json to arrays before we call the function if we need to.

After discussions with ajay and sankalp, we thought that maybe we shouldn't add too much code for specific projects to this repository. We discussed that we could have separate python packages for each project, and store them in the CompMusic orgnaisation.

**Comment by sertansenturk** [comment]
This code will not be included in Dunya
