### ISSUE TITLE
Incomplete taalas information returned

### ISSUE THREAD

**Issue by ajaysmurthy** [MTG/pycompmusic#11]
The API call to retrieve taalas of recordings in a release/concert returns incomplete information. 
e.g. 
``` python
from compmusic import dunya as dn
from compmusic.dunya import carnatic as ca
concert = ca.get_concert('955c8fc1-3c89-4e22-a894-9ad0cccdbaa8')
recordings = concert['recordings']
for rec in recordings:
    tala = ca.get_recording(rec['mbid'])['taala']        
    title = ca.get_recording(rec['mbid'])['title']
    print title, tala
```
returns

```
Vanajaksha Ninne Nammiti {u'uuid': u'c788c38a-b53a-48cb-b7bf-d11769260c4d', u'name': u'\u0100di'}
Parvathi Ninnu Neranammiti None
Nannu Brova Neeku {u'uuid': u'c788c38a-b53a-48cb-b7bf-d11769260c4d', u'name': u'\u0100di'}
Paahi Maam Sri None
Eppadi Manam Thunindhadho {u'uuid': u'8c6c26db-e01a-4eef-ae0b-9f7e31a926e8', u'name': u'R\u016bpaka'}
Sudhaamayee {u'uuid': u'8c6c26db-e01a-4eef-ae0b-9f7e31a926e8', u'name': u'R\u016bpaka'}
Jaya Jaya Padmanabhanujese {u'uuid': u'c788c38a-b53a-48cb-b7bf-d11769260c4d', u'name': u'\u0100di'}
Enadhu Manam Kavalai {u'uuid': u'c788c38a-b53a-48cb-b7bf-d11769260c4d', u'name': u'\u0100di'}
Purahara Nandana {u'uuid': u'c788c38a-b53a-48cb-b7bf-d11769260c4d', u'name': u'\u0100di'}
Geetha Vaadya Natana None
Shloka Namaste Sarvalokana None
Nera Nammiti None
Kannanai Paadu Maname None
Devadi Devanukku Jaya Mangalam None
```
There are some missing taalas ('None'), while the release/concert (https://musicbrainz.org/release/955c8fc1-3c89-4e22-a894-9ad0cccdbaa8) has taalas for all recordings as work attributes. Can be reproduced with another release too: https://musicbrainz.org/release/c5dd06f4-b0f5-4f40-b335-2db7928b3ae4

**Comment by alastair** [comment]
We're not importing work attributes yet. This is waiting on mtg/dunya#213, which is now waiting for vignesh to finish adding forms before we do a new import.

**Comment by alastair** [comment]
Now that we have attributes set for releases this release has imported correctly. I'm doing some small changes to the importer, and will close this once I've confirmed that these changes are correct.

**Comment by alastair** [comment]
Fixed! All releases are importing now. Some of them probably need to wait for forms, and so I'll reimport tomorrow as well.
