### ISSUE TITLE
dunya.carnatic.get_recording throws 404

### ISSUE THREAD

**Issue by gopalkoduri** [MTG/pycompmusic#12]
Code: 

```python
from compmusic import dunya
dunya.set_token(<token>)
dunya.carnatic.get_recording('a05b885f-59af-4766-a82e-2fea4578cf08')
```

dunya.hindustani.get_recording works fine though.

**Comment by alastair** [comment]
Works now - perhaps this one hadn't been imported. I've imported it now and
the query works for me,
