### ISSUE TITLE
inconsistencies between musicbrainz and pycompmusic

### ISSUE THREAD

**Issue by altugkarakurt** [MTG/pycompmusic#13]
I have pulled the recording information of makam recordings and there were some inconsistencies between the obtained data and the MusicBrainz entry of the same recording. As an example, I am copying an example case below.

` makam.get_recording('7e360f95-f16c-4fae-88df-d6fee8d000a1') `

This returns an empty list for performers, while there actually is a performer entered on [MusicBrainz page of the recording](http://musicbrainz.org/recording/7e360f95-f16c-4fae-88df-d6fee8d000a1)

**Comment by alastair** [comment]
This week I will import the makam data again, and we can verify that the data has been added correctly.

In the future you can add issues to https://github.com/MTG/dunya - we keep track of all issues in this project.

**Comment by alastair** [comment]
This case is fixed
http://dunya.compmusic.upf.edu/api/makam/recording/7e360f95-f16c-4fae-88df-d6fee8d000a1

I'm re-importing all of the other items in the collection now.

**Comment by altugkarakurt** [comment]
Everything seems fine now. The missing artists in the case of my example do really appear with `instrument: None` attribute. Case closed.
