### ISSUE TITLE
generate score name from MB work ID

### ISSUE THREAD

**Issue by georgid** [MTG/pycompmusic#15]
For  makam:  Is there already a script to automatically generate the score name from the MB work ID. I need to generate the name of the score as it is in the dataset symbTr: 
e.g. 
input: f5a89c06-d9bc-4425-a8e6-0f44f7c108ef
output: nihavent--sarki--aksak--bakmiyor_cesm-i--haci_arif_bey
If not how can I create it? The trick is that turkish unicode characters are mapped to latin ones for the current  naming which I would like to preserve.

**Comment by alastair** [comment]
Yes! use https://github.com/MTG/pycompmusic/blob/master/compmusic/dunya/makam.py#L235
