### ISSUE TITLE
lyricsAlign ready to deploy locally

### ISSUE THREAD

**Issue by georgid** [MTG/pycompmusic#17]
Tested on kora wih one recording
/homedtic/georgid//env/bin/python /homedtic/georgid/AlignmentDuration/test/testLyricsAlign.py

on dunya server:
/homedtic/georgid//env/bin/python/env/bin/python /homedtic/georgid//env/bin/python/test2/pycompmusic/compmusic/extractors/makam/lyricsalign.py

NOTE: becasue line 95
`wavFileURI, created = util.docserver_get_wav_filename(musicbrainzid)` does not work without dunya, use instead line 97 
`        wavFileURI = download_wav(musicbrainzid, outputDir)`
for which ffmpeg might be needed.

**Comment by andrebola** [comment]
This is done. The extractor is workig on kora with the commit 524c4b836183427a54bbd491094d11ea7e102bb8 of the AlignmentDuration project.

**Comment by georgid** [comment]
UPDATE: latest stable commit 83736c8a1f906ac5035d81d270814fe68cf418f7
!!! When installing see file requirements and BUILD INSTRUCTIONS from  README. 
to test on kora check scripts/runOnServer
