### ISSUE TITLE
where is compmusic.extractors.makam.pitch.PitchExtractMakam ?

### ISSUE THREAD

**Issue by georgid** [MTG/pycompmusic#20]
I use `pitch.PitchExtractMakam.run()` to extact pitch from acapella recordings. The class disappeared in the latest version. Was it moved and renamed?

**Comment by sertansenturk** [comment]
As far as I know it was deprecated months ago, when we integrated [tomato](https://github.com/sertansenturk/tomato). You can either use from there or from the repository called [predominantmelodymakam](https://github.com/sertansenturk/predominantmelodymakam), which tomato imports for this specific task.
