### ISSUE TITLE
install scikits.audiolab needed for visualization of Spectrogram cannot be installed on Ubuntu 16.10

### ISSUE THREAD

**Issue by georgid** [MTG/pycompmusic#21]
although not in requirements, some pycompmusic modules depend on [audiolab](https://scikits.appspot.com/audiolab): for example in [audioimages](https://github.com/MTG/pycompmusic/blob/master/compmusic/extractors/audioimages.py)

I did in a virtual env:  `pip install scikits.audiolab`  
However the import in ipython still fails:
 
```
In [1]: import scikits.audiolab
ValueError                                Traceback (most recent call last)
<ipython-input-1-040a9a9135f6> in <module>()
----> 1 import scikits.audiolab

/home/georgid/.local/lib/python2.7/site-packages/scikits/audiolab/__init__.py in <module>()
     23 __version__ = _version
     24 
---> 25 from pysndfile import formatinfo, sndfile
     26 from pysndfile import supported_format, supported_endianness, \
     27                       supported_encoding, PyaudioException, \

/home/georgid/.local/lib/python2.7/site-packages/scikits/audiolab/pysndfile/__init__.py in <module>()
----> 1 from _sndfile import Sndfile, Format, available_file_formats, \
      2         available_encodings, sndfile_version
      3 from compat import formatinfo, sndfile, PyaudioException, PyaudioIOError
      4 from compat import supported_format, supported_endianness, supported_encoding

numpy.pxd in scikits.audiolab.pysndfile._sndfile (scikits/audiolab/pysndfile/_sndfile.c:9632)()

ValueError: numpy.dtype does not appear to be the correct type object

```

I tried the solution of manually installing libsnd 1.0.25:  proposed here: 
http://stackoverflow.com/questions/15186674/cant-import-audiolab-in-python
but still got same same error: 

Then I tried the other solution: to install pip with [this script](https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py) for [python2.6,](http://askubuntu.com/questions/686182/using-python-2-6-while-python-2-7-is-installed) However  I could not get `virtualenv -p python2.6` working with python 2.6 due to the fact [virtualenv uses python 3.0](https://www.mail-archive.com/search?l=ubuntu-bugs@lists.ubuntu.com&q=subject:%22%5C%5BBug+1398059%5C%5D+Re%5C%3A+virtualenv+%5C-p+python2.6+fails+with+ValueError%5C%3A+zero+length+field+name+in+format%22&o=newest&f=1)

**Comment by alastair** [comment]
Setting up dependencies on a fresh 16.04 installation doesn't cause me any problems (from http://cournape.github.io/audiolab/installing.html)

```
apt-get install -y python python-dev python-pip python-setuptools libsndfile-dev python-numpy
pip install --upgrade pip
pip install scikits.audiolab

root@4be79cc9932a:/# python
>>> import scikits.audiolab
/usr/local/lib/python2.7/dist-packages/scikits/audiolab/soundio/play.py:48: UserWarning: Could not import alsa backend; most probably, you did not have alsa headers when building audiolab
  warnings.warn("Could not import alsa backend; most probably, "
>>> [import fine]

```

I notice that you're installing into some kind of virtualenv (`/home/georgid/.local/lib/python2.7/`) and so I wonder if there's a problem with conflicts between local installation of numpy and the version that audiolab was linked against when compiled. Without seeing the installation log I can't make any comments on this. I recommend you double check your python/numpy installation.

**Comment by georgid** [comment]
it was a numpy problem really

**Comment by matthijsvk** [comment]
How did you solve this issue?

**Comment by alastair** [comment]
Do you have a specific problem installing pycompmusic? If not we can't help, sorry.
