### ISSUE TITLE
"with_bootlegs" has no effect on returned number of concerts 

### ISSUE THREAD

**Issue by sankalpg** [MTG/pycompmusic#5]
I believe there are several concerts which are not included in the Dunya carnatic collection because they are classified as bootlegs. "with_bootlegs" flag should return all the concerts in the collection but looks like it does not. 

from compmusic.dunya import carnatic as ca
con1 = ca.get_concerts(with_bootlegs=True)
len(con1)
Out[73]: 191
con1 = ca.get_concerts(with_bootlegs=False)
len(con1)
Out[75]: 191

Any ideas if this is a problem with the API or something else.

**Comment by alastair** [comment]
Maybe this is a problem with the get_concerts() method. You can try
get_concert(mbid) with a release that you know is a bootleg. If you get 404
then you need to check that you're using an api token which is a staff
member. You can also check this url on the main dunya site to see if it
loads the page and tells you that it's a bootleg (
http://dunya.compmusic.upf.edu/carnatic/concert/mbid)

**Comment by alastair** [comment]
The problem is actually that I didn't import the bootleg recordings into dunya.
After talking with sankalp, I have some new tasks to do (import new concerts that have been added in the last 12 months; integrate bootlegs with plans for the makam bootleg collection code)
