### ISSUE TITLE
Slugify while downloading makam recordings and releases

### ISSUE THREAD

**Issue by sertansenturk** [MTG/pycompmusic#6]
Some earlier versions of several software (Audacity, MATLAB ...) might act unexpectedly when the names of the files have Turkish characters.

While we are using the functions makam.download_release() or makam.download_recording() can we make an optional boolean argument to slugify the downloaded paths?

If yes, I'm currently using the slugify_tr function provided in the extras of the unicode_tr package (https://github.com/emre/unicode_tr), which works perfectly.

**Comment by alastair** [comment]
Not a problem. Do you want to do it?
We need to know the license of the code before we use it. Can you please
open an issue with that project asking what the license is?

**Comment by alastair** [comment]
You could also consider using `unidecode`, which I think might already be a
dependency.
